name: Ridge Regression
type:
  _target_: train.ridge_v1
  alpha:
    low: 0.1
    high: 10
    step: 0.1
  random_state: ${random_state}

inference: 
  _target_: train.ridge_v1
  alpha: 0.1
  random_state: ${random_state}

clip: False